spring.application.name=ms-account-service
server.port=8081
spring.mvc.servlet.path=/api/ms-account-service

# Swagger / OpenAPI
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.operationsSorter=method

# DataSource
spring.datasource.url=jdbc:postgresql://localhost:5432/ms_account_db
spring.datasource.username=postgres
spring.datasource.password=12345
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=false
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Kafka
spring.kafka.bootstrap-servers=localhost:9092
spring.kafka.consumer.group-id=ms-account-service-group
spring.kafka.consumer.auto-offset-reset=earliest
spring.kafka.consumer.key-deserializer=org.apache.kafka.common.serialization.StringDeserializer
spring.kafka.consumer.value-deserializer=org.springframework.kafka.support.serializer.JsonDeserializer
spring.kafka.consumer.properties.spring.json.trusted.packages=com.sofka.ms_account_service.infrastructure.kafka.dto
spring.kafka.consumer.properties.spring.json.value.default.type=com.sofka.ms_account_service.infrastructure.kafka.dto.CustomerEvent

# Kafka Topics
kafka.topics.customer-events=customer-events
